### ISSUE TITLE
doc: Add KDoc and dokka

### ISSUE THREAD

**Issue by ybelMekk** [navikt/mock-oauth2-server#268]
No JavaDocs on any of the methods in MockOAuth2Server, which unfortunately makes this library nearly unusable, unless one study its source code @arcuri82

**Comment by jksolbakken** [comment]
Kind of late to the party here, but here are my two cents. The lack of comments/javadoc-y things is intentional. The need for such comments is a tell-tale sign of having the wrong abstractions and/or types. If you point us to the specific parts of the code you find difficult we may try to remodel them, but as for adding boilerplate comments I say 👎

**Comment by arcuri82** [comment]
> you point us to the specific parts of the code

@jksolbakken practically everything? 

just to give an example, what does `fun issuerUrl(issuerId: String): HttpUrl` do? does it register a known user in the server? does it look up a registered user and return an URL to locate his/her information?  the name of the function has only nouns, no verbs, so no idea what it is supposed to do. But if I dig in the code, I see a `= url(issuerId)` implementation, so I guess it is just converting from `String` to `HttpUrl`? but then, in the input parameter name `issuerId` there is no info about the fact that it is supposed to be a URL. 

In the end, this is your library, I am just providing some feedback, so not going to start a long discussion about documentation. I assume that, when you use a library, you never read their JavaDocs to learn how to use it? Another example, in Kotlin, you didn't need to read the documentation of what a `flatMap` does, you just understood it by its signature? That would be impressive :)

**Comment by tronghn** [comment]
Being a mock server, you could deduce that a function named `fun issuerUrl(issuerId: String): HttpUrl` constructs a `HttpUrl` for a given `issuerId` for this specific instance of the server (as mock servers usually run on random ports). Of course, this intuition also does require that you have some working knowledge of OAuth in order to understand why you would need an "issuer URL" in the first place.

That being said, what is obvious to us might not be obvious to everyone else, which is why documentation with that extra bit of context that eliminates any doubt can be useful, and something we should consider.

Off-topic: 
While I assume it isn't intended, the tone in some of these comments can be interpreted as overly passive aggressive.

This is an open source library. It is provided for free. It is open for suggestions and contributions from the public. We are not paid to maintain or support this library - it is all done pro bono, sometimes during paid hours, sometimes in our own free time. Using phrases such as "unusable" and "PITA" isn't constructive, nor is it very encouraging for us as maintainers.

**Comment by arcuri82** [comment]
hi @tronghn  
thanks for the feedback on the feedback. indeed, re-reading them, I see why what I wrote might be interpreted as passive aggressive, which was not intentional. If that was the case, I apologize for that
