### ISSUE TITLE
[Question] What is the easiest way to support https?

### ISSUE THREAD

**Issue by janhoy** [navikt/mock-oauth2-server#45]
Cannot see this question answered in docs or other issues. And I don't have access to project slack space, so therefore a new issue.

I need to specifically test an application's ability to talk HTTPS with the OAuth server, and trust custom SSL certificates. So I started with this project and got it setup quite easily with http. But now I am struggling to make the server listen over https with a custom SSL cert. I hoped the project would either just generate some certs and let me fetch the PEM or have some constructor that takes a cert and private-key and then use that. But turns out I need to write a new wrapper (`MockHttpServerHttpsWrapper`) that sets up SSLContext and everything.

I'm almost there, after fighting some dependency version clashes, I'm currently stuck in translating some of the Kotlin extension code to Java (my project uses Java).

So my question is - have you tried this? What is the recommended route? Is an official Https wrapper on the roadmap? Would it be easier with Netty?

**Comment by tommytroen** [comment]
@janhoy You are right, we haven't documented this as we have considered it to be out of scope so far, however I can see the use case for https in tests also. Can you use the docker approach for this or are you dependent on having an instance of the server in your java code?

I tested enabling HTTPS by using `docker-compose` and `nginx-proxy` (https://github.com/nginx-proxy/nginx-proxy) as a reverse proxy in front of the server, it seems to work fairly well both in the browser and within the docker network (container to container).


For example you can create a custom host by adding an entry in your `/etc/hosts` file:
`127.0.0.1 mockoauth2server`

Then create a selfsigned cert (you can use LetsEncrypt for this aswell, I opted for the easy approach in my test):
```
mkdir certs && cd certs
openssl req -x509 -newkey rsa:4096 -keyout mockoauth2server.key -out mockoauth2server.crt -days 365 -nodes -subj '/CN=mockoauth2server'
```

Then setup the `docker-compose.yml` file with:

```yaml
services:
  ingress:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
    hostname: mockoauth2server

  server:
    image: ghcr.io/navikt/mock-oauth2-server:0.3.3
    ports:
      - "81:8080"
    environment:
      - VIRTUAL_HOST=mockoauth2server

  debug:
    image: oyvindio/debug@sha256:e5861330dd71e22e57494d75f70a2cdb0567b17a0950fd7dec87836dde2e9ff6

```
* nginx-proxy acting as an `ingress` 
  * expose 80 and 443 ports
  * mount in the created keys
  * set hostname for the container (I had to do this in order to get container to container networking to work) 
* the mock-oauth2-server as the backend `server`
  * the environment var `VIRTUAL_HOST` must be set to match what you want to use as the hostname when invoking the proxy/server (nginx-proxy will automatically route any request to e.g. `mockoauth2server` to the server by using VIRTUAL_HOST)
* a `debug` container for testing container to container networking (this would typically be you client under test)
  * just `exec` into the container and `curl` the server to test if everything is working

When testing in the browser just go to e.g: https://mockoauth2server/default/.well-known/openid-configuration and it should work fine (with the exception of having to accept a self-signed cert)

For testing within the docker network you can exec into the debug container and curl the well-known endpoint:

```
▶ docker exec -it a571554b0b68  bash
root@a571554b0b68:/# curl -v -k https://mockoauth2server/default/.well-known/openid-configuration
* Hostname was NOT found in DNS cache
*   Trying 172.25.0.4...
* Connected to mockoauth2server (172.25.0.4) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
*        subject: CN=mockoauth2server
*        start date: 2021-05-27 09:25:26 GMT
*        expire date: 2022-05-27 09:25:26 GMT
*        issuer: CN=mockoauth2server
*        SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /default/.well-known/openid-configuration HTTP/1.1
> User-Agent: curl/7.38.0
> Host: mockoauth2server
> Accept: */*
>
< HTTP/1.1 200
* Server nginx/1.19.10 is not blacklisted
< Server: nginx/1.19.10
< Date: Thu, 27 May 2021 09:36:31 GMT
< Content-Type: application/json;charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Strict-Transport-Security: max-age=31536000
<
{
  "issuer" : "https://mockoauth2server/default",
  "authorization_endpoint" : "https://mockoauth2server/default/authorize",
  "end_session_endpoint" : "https://mockoauth2server/default/endsession",
  "token_endpoint" : "https://mockoauth2server/default/token",
  "jwks_uri" : "https://mockoauth2server/default/jwks",
  "response_types_supported" : [ "query", "fragment", "form_post" ],
  "subject_types_supported" : [ "public" ],
  "id_token_signing_alg_values_supported" : [ "RS256" ]
* Connection #0 to host mockoauth2server left intact
}
```

**Comment by tommytroen** [comment]
To answer the question about enabling HTTPS without docker I think the Netty wrapper would probably be easiest approach. It's not currently on our roadmap to create a https wrapper, but we can most certainly consider it.  I'll have a quick look and get back to you.

**Comment by janhoy** [comment]
Thanks for the reply. For this particular project it will run as part of an ordinary JUnit test so terminating SSL with nginx-proxy is unfortunately not a viable solution. I've used that solution in other projects though.

I might attempt a PR for this..

**Comment by tommytroen** [comment]
@janhoy PRs are welcomed 😄 I was a bit intrigued by this so I started a new branch here for the NettyWrapper: https://github.com/navikt/mock-oauth2-server/compare/support_https?expand=1

Haven't run a full integration test with https enabled though - but the NettyWrapper behaves as expected with HTTPS.

**Comment by janhoy** [comment]
I discovered that the `MockWebServerWrapper`was not as closed as I thought, and was able to get and modify the inner `MockWebServer` like this

```
MockWebServerWrapper mockWebServerWrapper = new MockWebServerWrapper();
MockWebServer mockWebServer = mockWebServerWrapper.getMockWebServer();
...
mockWebServer.useHttps(...);
```

So I now have it serve a HTTPs address for me. Still got some work left to add correct certificate trust to my test method, getting `javax.net.ssl.SSLHandshakeException`, but I think I have what I need without extending your library. This can of course be documented with examples for Java and Kotlin. This lets me bring my own certs. Would of course be fantastic if the Mock allowed auto-generating certs as well, but you'd need BouncyCastle for that I guess.

**Comment by janhoy** [comment]
I have now successfully completed my integration with the workaround mentioned above, so I'll close this issue.

I guess you could do almost identical change to the constructor of MockWebServerWrapper and thus support same style configuration across both.
